config/routes.rb
Rails.application.routes.draw do

resources :actors

	patch 'add_owner', :action => :add_ownership_to_ownerable, :controller => :owners
resources :owners do
	patch 'add_owner', :action => :add_ownership_to_ownerable
	member do
		patch 'add_owner', :action => :add_ownership_to_ownerable
	end
end

resources :requests do
	member do
		patch 'add_actors', :action => :add_actors_to_request 
	end
	resource :business_context do
		resources :owners
	end	
	resources :actors do
		delete 'unlink',:on => :member,:controller => :requests, :action => :remove_actor_from_request 
	end
	resources :flows
	resources :owners
end
resources :business_context do 
	resources :headings, only: [:new,  :edit, :show, :create, :destroy] do
		resources :uploads, only: [:new, :index]
	end
	resources :owners
end
resources :headings, only: [:update] do
	resources :uploads
end
root 'requests#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :request_actors
	has_many :requests, through: :request_actors
	has_many :flow_provider
	has_many :flow_consumer
	has_many :flows_as_provider, through: :flow_provider , source: :flow
	has_many :flows_as_consumer, through: :flow_consumer, source: :flow

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/business_context.rb
class BusinessContext < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :headerable
  accepts_nested_attributes_for :headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/context.rb
class Context < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :ch_context
	accepts_nested_attributes_for :headings, :allow_destroy => true

#  has_many :custom_headings, as: :ch_context
 # accepts_nested_attributes_for :custom_headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings
end

app/models/flow.rb
class Flow < ActiveRecord::Base
	has_many :consumers, :through => :flow_consumers, :source => :actor
	has_many :providers, :through => :flow_providers, :source => :actor

	has_many :flow_consumers
	has_many :flow_providers

	belongs_to :request
	
end

app/models/flow_consumer.rb
class FlowConsumer < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/flow_provider.rb
class FlowProvider < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :headerable, polymorphic: true
	has_many :uploads
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :ownerships
  #has_many :ownerables, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :requests, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :business_contexts, through: :ownerships, source: :ownerable, source_type: 'BusinessContext'
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :ownerable, polymorphic: true
	belongs_to :owner
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_one :business_context, :class_name => "BusinessContext"
	validates :name, presence: true, length: { minimum: 5 }

	has_many :request_actors
	has_many :actors, through: :request_actors

	has_many :flows

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships 
  	accepts_nested_attributes_for :ownerships, :allow_destroy => true
end

app/models/request_actor.rb
class RequestActor < ActiveRecord::Base
	belongs_to :actor
	belongs_to :request
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	#has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	belongs_to :heading
	has_attached_file :attachment

	validates_attachment	:attachment,
				:precense => true,
				content_type: { content_type: ["image/jpg","image/jpeg","image/png","image/bmp","image/gif",
				"application/x-visio",
				"application/msword",
				 "application/pdf",
				"application/excel",
				"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
				"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				"application/vnd.ms-powerpoint",
				"application/vnd.openxmlformats-officedocument.presentationml.presentation" ]}
end

app/controllers/bc_controller.rb
class BcController < ApplicationController
	def index
	end
	def new
	end
	def create
		@request = Request.find(params[:request_id])
		@bc = @request.bc.create(business_context_params)

		redirect_to request_path(@request) 
	end
	def show
		@bc = Bc.find(params[:id])
	end
	private
		def business_context_params
			params.require(:bc).permit(:as_is_imgage, :description, :as_is_description, :to_be_image, :to_be_description)
		end
	
end

app/controllers/headings_controller.rb
class HeadingsController < ApplicationController

	@disable_nav = true
	#before_action :all_headings, only: [:index, :create, :update, :destroy]
	#before_action :set_headings, only: [:edit, :update, :destroy]
	respond_to :html, :js
	
	def show
		@heading = Heading.find(params[:id])
		@uploads = @heading.uploads.all
		@disable_nav = true
	end

	def new
		@headerable= find_headerable
		@heading = @headerable.headings.new
#		@heading = Heading.new
	
	end

	def create 
		@headerable = find_headerable
		@heading = @headerable.headings.create(heading_params)
		
		# returnera alla headings till viewn
		#
		@headings = @headerable.headings.all
		#if @heading.save
		#	redirect_to context_url(context)
		#end
	end
	
	def edit
		@heading = Heading.find(params[:id])
		@disable_nav = true
	end

	def update
		#@context = find_context
		@heading = Heading.find(params[:id])
		@headerable = @heading.headerable
		if @heading.update_attributes(heading_params)
		end
	end
	
	def destroy
		heading = Heading.find(params[:id])
		@heading_id = heading.id
		heading.destroy
	end

	private
		#Hämta de skickade parametrarna
		def heading_params
			params.require(:heading).permit!
		end
		
		#MAGIC
		#hittar vilken model det är
		#ex. /requests/13/  business_context   /  5
		#			context_type	context_id
		def find_context
			@klass = params[:headerable_type].capitalize.constantize
			@context = klass.find(params[:headerable_id])
		end
		def find_headerable
		    params.each do |name, value|
		      if name =~ /(.+)_id$/
			return $1.classify.constantize.find(value) 
		      end
		     end
		    nil 
		end		
		
		def all_headings
			find_headerable.headings.all
		end
		def set_headings 
			@heading = Headings.find(params[:heading_id])
		end
end

app/helpers/actor_selector.rb
module NavLinkHelper
	#Denna modulen tar in link_text och link_path
	#http://stackoverflow.com/questions/3705898/best-way-to-add-current-class-to-nav-in-rails-3
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
		    link_to link_text, link_path
		end
	end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/bc_helper.rb
module BcHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/headings/_edit_form.html.erb
<div class="row">
  <%= form_for @heading, html: {class: 'form-horizontal'}, url: heading_path(@heading), remote: true do |f| %>
  <div class="col-xs-12 col-sm-12" >
    <section class ="panel panel-primary">
      <header class="panel-heading">
        <div class="row">
          <div class="col-xs-5">
              <div class="field form-group">
                  <%= f.text_field :title, class: 'form-control' %>
              </div>
          </div>
          <div class="col-xs-5">
          </div>
          <div class="col-xs-2">

          </div>
        </div>
      </header>
      <div class="panel-body">
        <div class="field form-group">
          <div class="col-sm-10">
            <%= f.text_area :text, class: 'form-control tinymce', :rows => 10 , :cols => 120 %>
          </div>
        </div>
      </div>
      <div class="actions form-group">
        <div class="col-sm-offset-1 col-sm-10">
              <%= f.submit %>
        </div>
      </div>
    <% end %>
      <div class="panel-footer">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-xs-2 col-xs-offset-5">
                <span class="text-muted">Attachments</span>
              </div>
            </div>

              <div class="col-xs-12">
                <div id="heading-uploads-<%= @heading.id %>">
                  <div class="row">
                    <%= render @heading.uploads , :heading => @heading ,edit: :true%>
                  </div>
                </div>
              </div>

          </div>
        </div>
        </div>
    </section>
  </div>
</div>
<div id="upload-form-<%= @heading.id%>" >
	<%= form_for @heading.uploads.new, html: { multipart: true , class: "dropzone"},url: heading_uploads_path(@heading), remote: true do |f|  %>
		<div class="fallback panel p-a-2">
			<%= f.text_field :name %><br>
			<%= f.label :attachment %><br>
			<%= f.file_field :attachment %><br>
			<%= f.submit "Upload" %>
		</div>
	<% end %>
</div>

app/views/headings/_form.html.erb
<h3>New Heading</h3>
<%= form_for [@headerable,@heading], html: {class: 'form-horizontal'}, url: business_context_headings_path(@headerable, @heading), remote: true do |f| %>
	<div class="field form-group">
		<%= f.label :title , class: 'col-sm-1 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :title, class: 'form-control' %>
		</div>
	</div>	
	<div class="field form-group">
		<%= f.label :text, class: 'col-sm-1 control-label' %>
		<div class="col-sm-10">
			<%= f.text_area :text, class: 'form-control' %>
		</div>
	</div>
	<div class="actions form-group">
		<div class="col-sm-offset-1 col-sm-10">
		      <%= f.submit %>
		</div>
	</div>
<% end %>

app/views/headings/_heading.html.erb
<div heading-id="<%= heading.id %>" >
	<div class="row">
		<div class="col-xs-12 col-sm-12" >
			<section class ="panel panel-primary">
				<header class="panel-heading">
					<div class="row">
						<div class="col-xs-10">
							<h1 class="panel-title" ><%= heading.title %></h1>
						</div>
						<div class="col-xs-2">
							<%= link_to edit_business_context_heading_path(@headerable, heading), remote: true , :class=>'btn btn-default btn-small' do %>
								<i class="glyphicon glyphicon-pencil"></i>
							<% end %>
							<%= link_to business_context_heading_path(@headerable,heading), remote: true, method: :delete,data: {confirm: 'Are you sure?' }, :class=>'btn btn-default' do %>
								<i class="glyphicon glyphicon-trash"></i>
							<% end %>
						</div>
					</div>
				</header>
				<div class="panel-body">
					<%= simple_format(heading.text) %>
				</div>
				<div class="panel-footer">
					<div class="row">
						<div class="col-sm-12">
                <div class="row">
                  <div class="col-xs-2 col-xs-offset-5">
                    <span class="text-muted">Attachments</span>
                  </div>
                </div>
                <div id="heading-uploads-<%= heading.id %>">
                  <div class="row">
                    <%= render heading.uploads , :heading => heading, :edit => false%>
                  </div>
                </div>
                <div id="upload-form-<%= heading.id%>" >
                  <% if false %>
                    <%= form_for heading.uploads.new, html: { multipart: true , class: "dropzone"},url: heading_uploads_path(heading), remote: true do |f|  %>
                      <div class="fallback panel p-a-2">
                          <%= f.label :attachment %><br>
                          <%= f.file_field :attachment %><br>
                          <%= f.submit "Upload" %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/headings/create.js.erb
$('#headings').html("<%= j (render partial: @headings) %>");
$('#heading-form').slideUp(350);

app/views/headings/destroy.js.erb
$('div[heading-id="<%= @heading_id %>"]').html("");

app/views/headings/new.js.erb
$('#heading-form').html("<%= j (render 'form') %>");
$('#heading-form').slideDown(350);

app/views/headings/update.js.erb
//$('#headings').html("<%= j (render @heading) %>");
$('div[heading-id="<%= @heading.id %>"]').replaceWith("<%= j (render @heading) %>");
$('#heading-form').slideUp(350);