config/routes.rb
Rails.application.routes.draw do

resources :actors

	patch 'add_owner', :action => :add_ownership_to_ownerable, :controller => :owners
resources :owners do
	patch 'add_owner', :action => :add_ownership_to_ownerable
	member do
		patch 'add_owner', :action => :add_ownership_to_ownerable
	end
end

resources :requests do
	member do
		patch 'add_actors', :action => :add_actors_to_request 
	end
	resource :business_context do
		resources :owners
	end	
	resources :actors do
		delete 'unlink',:on => :member,:controller => :requests, :action => :remove_actor_from_request 
	end
	resources :flows
	resources :owners
end
resources :business_context do 
	resources :headings, only: [:new,  :edit, :show, :create, :destroy] do
		resources :uploads, only: [:new, :index]
	end
	resources :owners
end
resources :headings, only: [:update] do
	resources :uploads
end
root 'requests#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :request_actors
	has_many :requests, through: :request_actors
	has_many :flow_provider
	has_many :flow_consumer
	has_many :flows_as_provider, through: :flow_provider , source: :flow
	has_many :flows_as_consumer, through: :flow_consumer, source: :flow

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/business_context.rb
class BusinessContext < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :headerable
  accepts_nested_attributes_for :headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/context.rb
class Context < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :ch_context
	accepts_nested_attributes_for :headings, :allow_destroy => true

#  has_many :custom_headings, as: :ch_context
 # accepts_nested_attributes_for :custom_headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings
end

app/models/flow.rb
class Flow < ActiveRecord::Base
	has_many :consumers, :through => :flow_consumers, :source => :actor
	has_many :providers, :through => :flow_providers, :source => :actor

	has_many :flow_consumers
	has_many :flow_providers

	belongs_to :request
	
end

app/models/flow_consumer.rb
class FlowConsumer < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/flow_provider.rb
class FlowProvider < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :headerable, polymorphic: true
	has_many :uploads
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :ownerships
  #has_many :ownerables, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :requests, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :business_contexts, through: :ownerships, source: :ownerable, source_type: 'BusinessContext'
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :ownerable, polymorphic: true
	belongs_to :owner
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_one :business_context, :class_name => "BusinessContext"
	validates :name, presence: true, length: { minimum: 5 }

	has_many :request_actors
	has_many :actors, through: :request_actors

	has_many :flows

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships 
  	accepts_nested_attributes_for :ownerships, :allow_destroy => true
end

app/models/request_actor.rb
class RequestActor < ActiveRecord::Base
	belongs_to :actor
	belongs_to :request
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	#has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	belongs_to :heading
	has_attached_file :attachment

	validates_attachment	:attachment,
				:precense => true,
				content_type: { content_type: ["image/jpg","image/jpeg","image/png","image/bmp","image/gif",
				"application/x-visio",
				"application/msword",
				 "application/pdf",
				"application/excel",
				"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
				"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				"application/vnd.ms-powerpoint",
				"application/vnd.openxmlformats-officedocument.presentationml.presentation" ]}
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

	helper :form_for_actor
	respond_to :html, :js
  def index
	if (params.has_key?(:request_id)) 
		@request = Request.find(params[:request_id])
		@actors = @request.actors.all
	else
		@actors = Actor.all
		@disable_nav = true
	end
  end

  def show
	if (params.has_key?(:request_id))
		@request = Request.find(params[:request_id])
		@actor = @request.actors.find(params[:id])
	else 
		@actor = Actor.find(params[:id])
		@disable_nav = true
	end
  end

  def new
	if (params.has_key?(:request_id))
		@request = Request.find(params[:request_id])
		@actor = @request.actors.new
	else	
		@actor = Actor.new
		@disable_nav = true
	end
  end

  def create
	if (params.has_key?(:request_id))
		@request = Request.find(params[:request_id])
		if @request.actors.create(actor_params)
			@actors = @request.actors.all
		end
	else
		if Actor.create(actor_params)
			@actors = Actor.all
		end
	end
#	if @actor.save 
#		if (params.has_key?(:request_id))
#			redirect_to request_actor_path(@request,@actor)
#		else
#			redirect_to @actor
#		end
#	else
#		if (params.has_key?(:request_id))
#			redirect_to new_request_actor_path(@request)
#		else
#			redirect_to 'new'
#		end
#	end
	@disable_nav = true
  end
  
  def edit
	if (params.has_key?(:request_id))
		@request = Request.find(params[:request_id])
	end
	@actor = Actor.find(params[:id])
	@disable_nav = true
  end 
  def update
	@actor = Actor.find(params[:id])
	if (params.has_key?(:request_id))
		@request = Request.find(params[:request_id])
		if @actor.update(actor_params)
			render 'update', :locals => {:unlink => true}
		end
	else
		@actor.update(actor_params)
	end
	
  end

  def destroy
	actor = Actor.find(params[:id])
	@actor_id = actor.id
	actor.destroy
	
  end


	private
		def actor_params
			params.require(:actor).permit!
		end
	
end

app/controllers/bc_controller.rb
class BcController < ApplicationController
	def index
	end
	def new
	end
	def create
		@request = Request.find(params[:request_id])
		@bc = @request.bc.create(business_context_params)

		redirect_to request_path(@request) 
	end
	def show
		@bc = Bc.find(params[:id])
	end
	private
		def business_context_params
			params.require(:bc).permit(:as_is_imgage, :description, :as_is_description, :to_be_image, :to_be_description)
		end
	
end

app/helpers/actor_selector.rb
module NavLinkHelper
	#Denna modulen tar in link_text och link_path
	#http://stackoverflow.com/questions/3705898/best-way-to-add-current-class-to-nav-in-rails-3
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
		    link_to link_text, link_path
		end
	end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/bc_helper.rb
module BcHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/actors/_actor.html.erb
<div actor-id="<%= actor.id %>">
	<div class="col-xs-12 col-sm-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-sm-7">
						<%= actor.name%>
					</div>
					<div class="col-sm-5 ">
						<%if params.has_key?(:request_id) || local_assigns.has_key?(:unlink) %>
							<%= link_to '', unlink_request_actor_path(@request, actor),
								method: :delete,
								data: {confirm: 'Are you sure?'},
								class: 'btn btn-default glyphicon glyphicon-remove-sign', 
								remote: true %>
						
							<%= link_to '', edit_request_actor_path(@request, actor), 
								class: 'btn btn-default glyphicon glyphicon-pencil',
								unlink: true,
								remote: true %>
							
						<% else %>
							<%= link_to '', actor_path(actor),
								      method: :delete,
								      data: { confirm: 'Do you want to delete the Actor completely?' },
								      class: 'btn btn-default glyphicon glyphicon-trash', 
								      remote: true %>
							<%= link_to '', edit_actor_path(actor),
								class: 'btn btn-default glyphicon glyphicon-pencil', 
								remote: true %>
						<% end %>
					</div>
				</div>
			</div>
			<div class="panel-body">
						<p>Platform: <%= actor.platform %><br></p>
						<p>Protocol: <%= actor.protocol %><br></p>
			</div>
			<div class="panel-footer">
				<span class="text-muted">Owner:</span>
				<table id="owners">
				<%= render actor.owners , :ownerable => actor, :locals=> {:removeable => false}%>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/actors/_edit_form.html.erb
<div actor-id="<%= @actor.id %>">
	<div class="col-xs-12 col-sm-4">
		<div class="panel panel-info">
			<%= form_for @actor, html: {class: 'form-horizontal'}, url: actor_path(@actor, request_id: @request.id), remote: true do |f| %>
			<div class="panel-heading">
				<div class="row">
					<div class="col-sm-10">
						<%= f.text_field :name, class: 'form-control' %>
					</div>
				</div>
			</div>
			<div class="panel-body">
				<div class="field form-group">
					<div class="col-sm-4">
						<%= f.label :platform , class: 'col-sm-1 control-label' %>
					</div>
					<div class="col-sm-8">
						<%= f.text_field :platform, class: 'form-control' %>
					</div>
				</div>
				<div class="field form-group">
					<div class="col-sm-4">
						<%= f.label :protocol , class: 'col-sm-1 control-label' %>
					</div>
					<div class="col-sm-8">
						<%= f.text_field :protocol, class: 'form-control' %>
					</div>
				</div>
				<%= f.submit 'Save', class: 'btn btn-primary' %>
			</div>
			<% end %>
			<div class="panel-footer">
					<span class="text-muted">Owners:</span>
					<table id="owners">
						<%= render @actor.owners, :ownerable => @actor , :removeable => true%>
					</table>
					<%= render 'owners/existing_owners', :ownerable => @actor, :request => @request %>
			</div>
		</div>
	</div>
</div>

app/views/actors/_existing_actor.html.erb
<h4>Add existing Actor</h4>
<div class="row">
	<div class="col-sm-12">
		<%= form_for @request, :url => add_actors_request_path(@request), remote: true do |f| %>
			<% if @request.actors.empty? %>
				<%= f.collection_select :actor_ids, Actor.all, :id, :name, { include_blank: "Select an existing Actor/System"},{class: 'form-control'} %>
			<% else %>
				<%= f.collection_select :actor_ids, Actor.where('id NOT IN (?)',@request.actor_ids), :id, :name, { include_blank: "Select an existing Actor/System"},{class: 'form-control'} %>
			<% end %>
			<%= f.submit %>
		<% end %> 
	</div>				
</div>		

app/views/actors/_form.html.erb
<div class="row new-object">
	<div class="col-sm-4">
		<div class="row">
		<h4>New Actor</h4>
		<%= form_for_actor params.has_key?(:request_id)do |f| %>
			<div class="field form-group">
				<div class="col-sm-6">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>
			</div>
			<div class="field form-group">
				<div class="col-sm-6">
				<%= f.label :platform %>
					<%= f.text_field :platform %>
				</div>
			</div>
			<div class="field form-group">
				<div class="col-sm-6">
				<%= f.label :protocol %>
					<%= f.text_field :protocol %>
				</div>
			</div>
			<%= f.submit %>
		<% end %>
		</div>
	</div>
</div>

app/views/actors/_new.js.erb
$('#actor-form').html("<%= j (render 'form') %>");
$('#actor-form').slideDown(350);

app/views/actors/added_actors.js.erb
//$("#actors").replaceWith("<%= j (render @request.actors, unlink: true) %>");
$('div[actor-id="<%= @actor.id %>"]').replaceWith("<%= j (render @actor,request_id: request.id, unlink: true) %>");

app/views/actors/create.js.erb
$('#actors').html("<%= j (render @actors, show_unlink: true) %>");
$('#new-actor-form').slideUp(350);
$('#new-actor-button').toggleClass('btn-default');
$('#new-actor-button').toggleClass('btn-primary');
$('#new-actor-form').find('form').trigger("reset");

app/views/actors/destroy.js.erb
$('div[actor-id="<%= @actor_id %>"]').html("");

app/views/actors/edit.js.erb
$('div[actor-id="<%= @actor.id %>"]').replaceWith("<%= j (render 'edit_form') %>");

app/views/actors/index.html.erb
<div class="col-xs-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="row">
				<div class="col-sm-9 col-xs-12">
					<span class="text-muted"><b>Actors</b></span><br><br>
					<span>Actors is the Baseline naming convention for Systems and Applications acting in an integration. <br>In this section you include the actors involved in your integration request, i.e. the acting systems that this integration will cover. The selection of actors you make here will be available in the Data Flows section.</span><br><br>
					<span>You can choose from existing Actors from past integrations, or you can create new ones. </span>
				</div>
				<div class="col-sm-3 hidden-xs">
					<%= image_tag("actors", size: "130x130") %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-sm-12"class="row-bottom-20">
	<div class="row">
		<div class="col-sm-12">
			<% if params.has_key?(:request_id)  %>
				<%= link_to 'New Actor', new_request_actor_path , remote: true, id: 'new-actor-button', class: 'btn-primary btn'%>
				<%= button_tag 'Add existing Actor', id: 'existing-actor-button', class: 'btn btn-primary' %>
			<% else %>
				<%= link_to 'New Actor', new_actor_path , remote: true, id: 'new-actor-button', class: 'btn btn-primary'%>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div id="new-actor-form" class="new-form col-sm-6">
			<%= render 'actors/form' %>

		</div>
		<% if params.has_key?(:request_id)  %>
			<div id="existing-actor-form" class="new-form col-sm-4">
				<%= render 'existing_actor' %>
			</div>
		<% end %>
	</div>
</div>
	<div class="col-sm-12 row-top-20">
		<div id="actors">
			<%= render @actors %>
		</div>
	</div>

app/views/actors/new.js.erb
$('#actor-form').html("<%= j (render 'form') %>");
$('#actor-form').slideDown(350);

app/views/actors/show.html.erb
<%= render @actor %>
<p>
<% if params.has_key?(:request_id) %>
	<%= link_to 'Back', request_actors_path(@request) %>
<% else %>
	<%= link_to 'Back to index', actors_path %>
<% end %>
</p>

app/views/actors/update.js.erb
$('div[actor-id="<%= @actor.id %>"]').replaceWith("<%= j (render @actor,request_id: @request.id, unlink: true) %>");
$('#actor-form').slideUp(350);