config/routes.rb
Rails.application.routes.draw do

resources :actors

	patch 'add_owner', :action => :add_ownership_to_ownerable, :controller => :owners
resources :owners do
	patch 'add_owner', :action => :add_ownership_to_ownerable
	member do
		patch 'add_owner', :action => :add_ownership_to_ownerable
	end
end

resources :requests do
	member do
		patch 'add_actors', :action => :add_actors_to_request 
	end
	resource :business_context do
		resources :owners
	end	
	resources :actors do
		delete 'unlink',:on => :member,:controller => :requests, :action => :remove_actor_from_request 
	end
	resources :flows
	resources :owners
end
resources :business_context do 
	resources :headings, only: [:new,  :edit, :show, :create, :destroy] do
		resources :uploads, only: [:new, :index]
	end
	resources :owners
end
resources :headings, only: [:update] do
	resources :uploads
end
root 'requests#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :request_actors
	has_many :requests, through: :request_actors
	has_many :flow_provider
	has_many :flow_consumer
	has_many :flows_as_provider, through: :flow_provider , source: :flow
	has_many :flows_as_consumer, through: :flow_consumer, source: :flow

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/business_context.rb
class BusinessContext < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :headerable
  accepts_nested_attributes_for :headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/context.rb
class Context < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :ch_context
	accepts_nested_attributes_for :headings, :allow_destroy => true

#  has_many :custom_headings, as: :ch_context
 # accepts_nested_attributes_for :custom_headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings
end

app/models/flow.rb
class Flow < ActiveRecord::Base
	has_many :consumers, :through => :flow_consumers, :source => :actor
	has_many :providers, :through => :flow_providers, :source => :actor

	has_many :flow_consumers
	has_many :flow_providers

	belongs_to :request
	
end

app/models/flow_consumer.rb
class FlowConsumer < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/flow_provider.rb
class FlowProvider < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :headerable, polymorphic: true
	has_many :uploads
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :ownerships
  #has_many :ownerables, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :requests, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :business_contexts, through: :ownerships, source: :ownerable, source_type: 'BusinessContext'
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :ownerable, polymorphic: true
	belongs_to :owner
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_one :business_context, :class_name => "BusinessContext"
	validates :name, presence: true, length: { minimum: 5 }

	has_many :request_actors
	has_many :actors, through: :request_actors

	has_many :flows

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships 
  	accepts_nested_attributes_for :ownerships, :allow_destroy => true
end

app/models/request_actor.rb
class RequestActor < ActiveRecord::Base
	belongs_to :actor
	belongs_to :request
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	#has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	belongs_to :heading
	has_attached_file :attachment

	validates_attachment	:attachment,
				:precense => true,
				content_type: { content_type: ["image/jpg","image/jpeg","image/png","image/bmp","image/gif",
				"application/x-visio",
				"application/msword",
				 "application/pdf",
				"application/excel",
				"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
				"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				"application/vnd.ms-powerpoint",
				"application/vnd.openxmlformats-officedocument.presentationml.presentation" ]}
end

app/controllers/bc_controller.rb
class BcController < ApplicationController
	def index
	end
	def new
	end
	def create
		@request = Request.find(params[:request_id])
		@bc = @request.bc.create(business_context_params)

		redirect_to request_path(@request) 
	end
	def show
		@bc = Bc.find(params[:id])
	end
	private
		def business_context_params
			params.require(:bc).permit(:as_is_imgage, :description, :as_is_description, :to_be_image, :to_be_description)
		end
	
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
	before_action :get_request
  def index
	@flows = @request.flows.all
  end
  
  def show
	@flow = @request.flows.find(params[:id])
  end

  def new
	@flow = @request.flows.new
  end

  def create
	@flow = @request.flows.create(flow_params)
	if @flow.save
		redirect_to request_flows_path(@request)
	else
		redirect_to new_request_flow_path(@request)
	end
  end


  def edit
	@flow = @request.flows.find(params[:id])
  end

  def update
	@flow = @request.flows.find(params[:id])
	if @flow.update(flow_params)
		redirect_to request_flow_path(@flow)
	else
		redirect_to edit_request_flow_path(@flow)
	end
  end

  def destroy
	@flow = @request.flows.find(params[:id])
	if @flow.delete
		redirect_to request_flows_path
	else
	
	end
  end
	private 
	def flow_params
		params.require(:flow).permit!
	end
	def get_request
		@request = Request.find(params[:request_id])
	end
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
	before_action :get_request
	respond_to :html, :js
  def index
	@flows = @request.flows.all
  end
  
  def show
	@flow = @request.flows.find(params[:id])
  end

  def new
	@flow = @request.flows.new
  end

  def create
	#@flow.provider = Actor.find(flow_params.require(:provider))
	@flow = @request.flows.create(flow_params)
	@flows = @request.flows.all
  end


  def edit
	@flow = @request.flows.find(params[:id])
  end

  def update
	@flow = @request.flows.find(params[:id])
	@flow.update(flow_params)
  end

  def destroy
	@flow = @request.flows.find(params[:id])
	@flow_id = @flow.id
	@flow.delete
  end
	private 
	def flow_params
		params.require(:flow).permit(:name, :objective,:master_data,:frequency, :size,:security,:provider_ids,:consumer_ids, :provider_ids => [], :consumer_ids => [])
	end
	def get_request
		@request = Request.find(params[:request_id])
	end
end

app/helpers/actor_selector.rb
module NavLinkHelper
	#Denna modulen tar in link_text och link_path
	#http://stackoverflow.com/questions/3705898/best-way-to-add-current-class-to-nav-in-rails-3
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
		    link_to link_text, link_path
		end
	end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/bc_helper.rb
module BcHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flows/_edit_form.html.erb
<%= form_for @flow , :html => {:role => 'form'}, url: request_flow_path(@request, @flow), remote: true do |f| %>

      <div class="row">
        <div class="col-xs-12 col-sm-12" >
          <section class ="panel panel-primary">
            <header class="panel-heading">
              <div class="row">
                <div class="col-xs-5 col-xs-offset-4">
                  <h1 class="panel-title" ><%= f.text_field :name, class: 'form-control' %></h1>
                </div>
                <div class="col-xs-2">

                </div>
              </div>
            </header>
            <div class="panel-body">
              <div class="col-sm-3 ">
                <h4 class="text-muted">Provider(s)</h4>
                <%= f.collection_select :provider_ids, @request.actors.all, :id, :name, {},{class: 'form-control selectpicker', multiple: true}  %>
                <br>
              </div>
	      <div class="col-sm-6">
		      <div class="row">
				<h4 class="text-muted">Message</h4>
				<div class="col-sm-4">
				  Size: <%= f.select :size,
						     options_for_select([
									    ['< 1kb','< 1kb'],
									    ['< 1mb','< 1mb']
									]), {},{class: 'form-control'}%>
				</div>
				<div class="col-sm-4">
				  Security: <%= f.select :security,
							 options_for_select([
										['O','O'],
										['I','I'],
										['C','C']
									    ]), {},{class: 'form-control'}%>
				</div>
				<div class="col-sm-4">
					Masterdata: <br>
					Yes: 
					<%= f.radio_button :master_data, true, class: ''%>
					No
					<%= f.radio_button :master_data, false, class: ''%>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					Message Frequency: 
					<%= f.text_area :frequency, 
					class: 'form-control',
					:placeholder => "eg. Ranging from 1 message per hour up to 10 per minute."%>
				</div>
			</div>
              </div>
              <div class="col-sm-3 ">
                <h4 class="text-muted">Consumer(s)</h4>
                <%= f.collection_select :consumer_ids, @request.actors.all, :id, :name, { },{class: 'form-control',multiple: true} %>
                <br>
              </div>
            </div>
            <div class="panel-footer">
              <h4 class="text-muted">Objective</h4>
              <%= f.text_area :objective , class: 'form-control'%>

            </div>
          </section>
          <div class="row">
            <div class="col-sm-offset-4 col-sm-3">
              <%= f.submit class: "btn btn-primary btn-lg btn-block btn-info" %>


            </div>

          </div>
      </div>
<% end %>

app/views/flows/_flow.html.erb
<div flow-id="<%= flow.id %>">
  <div class="row">
    <div class="col-xs-12 col-sm-12" >
      <section class ="panel panel-primary">
        <header class="panel-heading">
          <div class="row">
            <div class="col-xs-5 col-xs-offset-5">
              <h1 class="panel-title" ><%= flow.name%></h1>
            </div>
            <div class="col-xs-2">
              <%= link_to '', request_flow_path(@request,flow),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: 'btn btn-default glyphicon glyphicon-trash', remote: true %>
              <%= link_to '', edit_request_flow_path(@request,flow),
                          class: 'btn btn-default glyphicon glyphicon-pencil', remote: true %>
            </div>
          </div>
        </header>
        <div class="panel-body">
          <div class="col-sm-3 ">
		  <h4 class="text-muted">Provider(s)</h4>
		  <table id="providers-table">
		    <% flow.providers.each do |f|%>
				    <tr>
					    <td><p><%= link_to f.name, request_actor_path(@request, f) %></p></td><td><p> :  <%= f.protocol %></p></td>
				    </tr>
				<% end %>
		</table>
            <br>
          </div>
          <div class="col-sm-6">
		  <div class="row">
		    <h4 class="text-muted">Message</h4>
		    <div class="col-sm-4">
		      <b>Size:</b> <%= flow.size %>
		    </div>
		    <div class="col-sm-4">
		      <b>Security:</b> <%= flow.security %>
		    </div>
		    <div class="col-sm-4">
	    <b>Master data?:</b>
	    <% if flow.master_data == true %>
		    Yes
	    <% else %>
			No
		<% end %>
		    </div>
	    </div><br>
			<div class="row">
				<div class="col-sm-12">
				   <b>Message Frequency:</b><br>
				   <%= flow.frequency %>
				</div>
			</div>
          </div>
          <div class="col-sm-3 ">
            <h4 class="text-muted">Consumer(s)</h4>
	    	<table id="consumers-table">
			<% flow.consumers.each do |f|%>
				<tr>
			                <td><p><%= link_to f.name, request_actor_path(@request, f) %></p></td><td><p> : <%= f.protocol %> </p></td>
				</tr>
              <% end %>
      </table>
            <br>
          </div>
			  </div>
        <div class="panel-footer">
            <h4 class="text-muted">Objective</h4>
            <%= flow.objective %>

        </div>
		  </section>
    </div>
	</div>
</div>

app/views/flows/_form.html.erb
<%= form_for @flow , :html => {:role => 'form'}, url: request_flows_path(@request), remote: true do |f| %>

      <div class="row">
        <div class="col-xs-12 col-sm-12" >
          <section class ="panel panel-success">
            <header class="panel-heading">
              <div class="row">
                <div class="col-xs-5 col-xs-offset-4">
                  <h1 class="panel-title" ><%= f.text_field :name, class: 'form-control', :placeholder => "DataFlowName" %></h1>
                </div>
                <div class="col-xs-2">

                </div>
              </div>
            </header>
            <div class="panel-body">
              <div class="col-sm-3 ">
                <h4 class="text-muted">Provider(s)</h4>
                <%= f.collection_select :provider_ids, @request.actors.all, :id, :name, {},{class: 'form-control selectpicker', multiple: true}  %>
                <br>
              </div>
	      <div class="col-sm-6">
		      <div class="row">
				<h4 class="text-muted">Message</h4>
				<div class="col-sm-4">
				  Size: <%= f.select :size,
						     options_for_select([
									    ['< 1kb','< 1kb'],
									    ['< 1mb','< 1mb']
									]), {},{class: 'form-control'}%>
				</div>
				<div class="col-sm-4">
				  Security: <%= f.select :security,
							 options_for_select([
										['O','O'],
										['I','I'],
										['C','C']
									    ]), {},{class: 'form-control'}%>
				</div>
				<div class="col-sm-4">
					Masterdata: <br>
					Yes: 
					<%= f.radio_button :master_data, true, class: ''%>
					No
					<%= f.radio_button :master_data, false, class: '', checked: true%>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					Message Frequency: 
					<%= f.text_area :frequency, 
					class: 'form-control',
					:placeholder => "eg. Ranging from 1 message per hour up to 10 per minute."%>
				</div>
			</div>
              </div>
              <div class="col-sm-3 ">
                <h4 class="text-muted">Consumer(s)</h4>
                <%= f.collection_select :consumer_ids, @request.actors.all, :id, :name, { },{class: 'form-control',multiple: true} %>
                <br>
              </div>
            </div>
            <div class="panel-footer">
              <h4 class="text-muted">Objective</h4>
              <%= f.text_area :objective , class: 'form-control' , :placeholder => "Describe the objective of this dataflow.." %>
		<div class="row">
			<div class="col-xs-1 col-xs-offset-10 row-top-20">
				  <%= f.submit class: 'btn btn-primary'%>
			</div>
		</div>
            </div>
          </section>
        </div>
      </div>
<% end %>

app/views/flows/create.js.erb
$('#flows').html("<%= j (render partial: @flows) %>");
$('#flow-form').slideUp(350);

app/views/flows/destroy.js.erb
$('div[flow-id="<%= @flow_id %>"]').html("");

app/views/flows/edit.js.erb
$('div[flow-id="<%= @flow.id %>"]').html("<%= j (render 'edit_form') %>");

app/views/flows/index.html.erb
<div class="col-xs-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="row">
				<div class="col-sm-9 col-xs-12">
					<span class="text-muted"><b>Data Flows</b></span><br><br>
					<span>You can choose from existing Actors from past integrations, or you can create new ones. </span>
				</div>
				<div class="col-sm-3 hidden-xs">
					<%#= image_tag("actors", size: "130x130") %>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="flows">
	<% @flows.each do |flow| %>
		<%= render flow %>
	<% end %>
</div>
<div id="flow-form">

</div>
<%= link_to new_request_flow_path, remote: true do %>
    <div class="col-sm-offset-4 col-sm-3">
      <button type="button" class="btn btn-primary btn-lg btn-block btn-info">New Dataflow</button>
    </div>
<% end %>

app/views/flows/new.js.erb
$('#flow-form').html("<%= j (render 'form') %>");
$('#flow-form').slideDown(350);

app/views/flows/show.html.erb
<%= render @actor %>
<p>
<% if params.has_key?(:request_id) %>
	<%= link_to 'Back', request_actors_path(@request) %>
<% else %>
	<%= link_to 'Back to index', actors_path %>
<% end %>
</p>

app/views/flows/update.html.erb
<h1>Actors#update</h1>
<p>Find me in app/views/actors/update.html.erb</p>

app/views/flows/update.js.erb
$('div[flow-id="<%= @flow.id %>"]').replaceWith("<%= j (render @flow) %>");
$('#flow-form').slideUp(350);