config/routes.rb
Rails.application.routes.draw do

resources :actors

	patch 'add_owner', :action => :add_ownership_to_ownerable, :controller => :owners
resources :owners do
	patch 'add_owner', :action => :add_ownership_to_ownerable
	member do
		patch 'add_owner', :action => :add_ownership_to_ownerable
	end
end

resources :requests do
	member do
		patch 'add_actors', :action => :add_actors_to_request 
	end
	resource :business_context do
		resources :owners
	end	
	resources :actors do
		delete 'unlink',:on => :member,:controller => :requests, :action => :remove_actor_from_request 
	end
	resources :flows
	resources :owners
end
resources :business_context do 
	resources :headings, only: [:new,  :edit, :show, :create, :destroy] do
		resources :uploads, only: [:new, :index]
	end
	resources :owners
end
resources :headings, only: [:update] do
	resources :uploads
end
root 'requests#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :request_actors
	has_many :requests, through: :request_actors
	has_many :flow_provider
	has_many :flow_consumer
	has_many :flows_as_provider, through: :flow_provider , source: :flow
	has_many :flows_as_consumer, through: :flow_consumer, source: :flow

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/business_context.rb
class BusinessContext < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :headerable
  accepts_nested_attributes_for :headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships
end

app/models/context.rb
class Context < ActiveRecord::Base
  belongs_to :request
  has_many :headings, as: :ch_context
	accepts_nested_attributes_for :headings, :allow_destroy => true

#  has_many :custom_headings, as: :ch_context
 # accepts_nested_attributes_for :custom_headings, :allow_destroy => true
						#allow_destroy måste finnas för att kunna ta bort custom_headings
end

app/models/flow.rb
class Flow < ActiveRecord::Base
	has_many :consumers, :through => :flow_consumers, :source => :actor
	has_many :providers, :through => :flow_providers, :source => :actor

	has_many :flow_consumers
	has_many :flow_providers

	belongs_to :request
	
end

app/models/flow_consumer.rb
class FlowConsumer < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/flow_provider.rb
class FlowProvider < ActiveRecord::Base
	belongs_to :actor
	belongs_to :flow
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :headerable, polymorphic: true
	has_many :uploads
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :ownerships
  #has_many :ownerables, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :requests, through: :ownerships, source: :ownerable, source_type: 'Request'
  has_many :business_contexts, through: :ownerships, source: :ownerable, source_type: 'BusinessContext'
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :ownerable, polymorphic: true
	belongs_to :owner
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_one :business_context, :class_name => "BusinessContext"
	validates :name, presence: true, length: { minimum: 5 }

	has_many :request_actors
	has_many :actors, through: :request_actors

	has_many :flows

	has_many :ownerships, :as => :ownerable
	has_many :owners, through: :ownerships 
  	accepts_nested_attributes_for :ownerships, :allow_destroy => true
end

app/models/request_actor.rb
class RequestActor < ActiveRecord::Base
	belongs_to :actor
	belongs_to :request
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	#has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	belongs_to :heading
	has_attached_file :attachment

	validates_attachment	:attachment,
				:precense => true,
				content_type: { content_type: ["image/jpg","image/jpeg","image/png","image/bmp","image/gif",
				"application/x-visio",
				"application/msword",
				 "application/pdf",
				"application/excel",
				"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
				"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				"application/vnd.ms-powerpoint",
				"application/vnd.openxmlformats-officedocument.presentationml.presentation" ]}
end

app/controllers/bc_controller.rb
class BcController < ApplicationController
	def index
	end
	def new
	end
	def create
		@request = Request.find(params[:request_id])
		@bc = @request.bc.create(business_context_params)

		redirect_to request_path(@request) 
	end
	def show
		@bc = Bc.find(params[:id])
	end
	private
		def business_context_params
			params.require(:bc).permit(:as_is_imgage, :description, :as_is_description, :to_be_image, :to_be_description)
		end
	
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	respond_to :html , :js
	def index
		@requests = Request.all
		@disable_nav = true
	end
	def show
		@request = Request.find(params[:id])
		@owners = @request.owners
	end
	def new
		@request = Request.new
		@disable_nav = true
	end
	def edit
		@request = Request.find(params[:id])
	end 
	def create
		@request = Request.new(request_create_params)
		
		if @request.save
			redirect_to @request
			#render 'show'
		else
			@disable_nav = true
			render 'new'
		end
		#Fyll business Context default
		@request.business_context = BusinessContext.create
		@request.business_context.headings.create(:title => "Description", :text => "")
		@request.business_context.headings.create(:title => "As-Is", :text => "")
		@request.business_context.headings.create(:title => "To-Be", :text => "")

		#Skapa Actors 
		@request.actors.build
	end
	def update
		@request = Request.find(params[:id])

		if @request.update(request_params)
			redirect_to @request
		else 
			render 'edit'
		end
	end
	def destroy
		request = Request.find(params[:id])
		request.destroy

		redirect_to action: "index"
	end
	
	#För att kunna addera existerande actors till requesten, istället för att skapa en identisk
	def add_actors_to_request 
		@request = Request.find(params[:id])
		actor_ids = params[:request][:actor_ids] 
		actors = Actor.where(id: actor_ids)
		if @request.actors << actors
			render :js => "window.location = '#{request_actors_path(@request)}'" 
			##render 'actors/added_actors', actors: @actors, request: @request
			#render 'actors/update'
		end
	end
	def remove_actor_from_request
		@request = Request.find(params[:request_id])
		actor_id = params[:id]
		if @request.actors.delete(Actor.find(actor_id))
			render :js => "window.location = '#{request_actors_path(@request)}'" 
		end
	end
	
	private 
		def request_create_params 
			params.require(:request).permit(:name, :description, :creation_date, :owner, :business_context)
		end
		def request_params 
			params.require(:request).permit(:name, :description, :creation_date, :owner, :business_context, :actors, :actor_ids, :actor_ids[])
		end

end

app/helpers/actor_selector.rb
module NavLinkHelper
	#Denna modulen tar in link_text och link_path
	#http://stackoverflow.com/questions/3705898/best-way-to-add-current-class-to-nav-in-rails-3
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
		    link_to link_text, link_path
		end
	end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/bc_helper.rb
module BcHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/requests/_form.html.erb
<%= form_for @request, html: {class: 'form-horizontal'} do |obj| %>
	<% if @request.errors.any? %>
		<div id="error_explanation">
		<%= pluralize(@request.errors.count, "error") %> errors.
		<ul>
			<% @request.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	<div class="field form-group">
		<%= obj.label :name ,class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= obj.text_field :name %>
		</div>
	</div>
	<div class="field form-group">
		<%= obj.label :owner ,class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= obj.text_field :owner %>
		</div>
	</div>
		
	<div class="actions form-group">
		<div class="col-sm-offset-2 col-sm-10">
		      <%= obj.submit 'Done', :class => 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/requests/edit.html.erb
<h1> Edit Request </h1>

<%= render 'form' %>
<%= link_to 'Back', request_path %>

app/views/requests/index.html.erb
<div class="col-sm-10">

<p> New Request 
<%= link_to new_request_path, :class=>'btn btn-default btn-xs' do %>
<i class="glyphicon glyphicon-plus"></i>
<% end %>
</p>
<h1>Listing requests</h1>
 
<table class="table table-condensed table-hover">
	<tr>
		<thead>
			<tr>
			<th>Integration</th>
			<th>Owner</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<tr>
		</thead>
	</tr>
  <% @requests.each do |request| %>
	<tr>
		<td><%= request.name %></td>
		<td><%= request.owner%></td>
		<td><%= request.created_at.strftime("%b %d, %Y")%></td>
		<td><%= link_to 'Show', request_path(request), :class => 'btn btn-default' %>  </td>  
		<td><%= link_to 'Edit', edit_request_path(request), :class => 'btn btn-default' %>  </td>
		<td><%= link_to 'Destroy', request_path(request), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, :class => 'btn btn-default'  %> </td>
	</tr>
  <% end %>
</table>

</div>

app/views/requests/new.html.erb
<h1> New Request </h1>

<%= render 'form' %>
<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<div class="row">

<div class="col-sm-10 headercontainer">
	<div class="col-sm-6">
		<h2><%= @request.name %> </h2>
	</div>
	<div class="col-sm-2 headerglyph">
		<%= link_to edit_request_path(@request), :class=>'btn btn-default' do %>
				<i class="glyphicon glyphicon-pencil"></i>
		<% end %>
	</div>
</div>

</div>
<div class="row">
	<br>
	<div class="row">
		<div class="col-sm-3 textleft">Project Manager:</div>
		<div class="col-sm-3 textright"><%= @request.owner %></div>
	</div>
	<div class="row">
		<div class="col-sm-3 textleft">Creation date:</div>	
		<div class="col-sm-3 textright"><%= @request.created_at %></div>
	</div>
	<div class="row">
		<div class="col-sm-6 ">
			<h3>Project Stakeholders</h3>
			<table id="owners">
				<%= render @request.owners, ownerable: @request, :small_owner => true, :removeable => true %>
			</table>
			<br>
			<%= render 'owners/form', ownerable: @request  %>
		</div>
	</div>
</div>